# .drone.yml

kind: pipeline
type: docker
name: default 

steps: 
  - name: flake8
    image: python:3.8    
    commands:
      - python -m pip install -r /django_practice/django_practice/requirements.txt
      - flake8 /django_practice/django_practice
    when:      
      event:      
        - push      
        - pull_request    
    volumes:      
        - name: pip_cache        
          path: /root/.cache/pip 
volumes:
  - name: pip_cache    
    host:      
      path: /tmp/cache/drone/pip