# docker-compose.yml
version: "3"
services:
  django:
    build:
        context: .
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:9000"

  drone-server:
    image: drone/drone:1
    container_name: drone-server
    ports:
      - 80:80
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_SERVER_HOST=65c0-125-228-171-25.jp.ngrok.io 
      - DRONE_SERVER_PROTO=https
      - DRONE_RPC_SECRET=f1390481f69c7c5dc18f954f3e7b6445
      - DRONE_GITHUB_CLIENT_ID=7c5c0377304b1b84074a
      - DRONE_GITHUB_CLIENT_SECRET=cfe4f24e3dde0920268ca9d9383f1fdd34a01e5c
      - DRONE_USER_CREATE=username:sean85120,admin:true

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=f1390481f69c7c5dc18f954f3e7b6445
      - DRONE_RUNNER_CAPACITY=2
