# docker-compose.yml

version: '2' 
services:  
  drone-server:    
    image: drone/drone:1
    ports:      
      - "80:80"    
    volumes:      
      - ${DRONE_DATA}:/data      
      - /var/run/docker.sock:/var/run/docker.sock    
    restart: always    
    environment:      
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}      
      - DRONE_SERVER_PROTO=http
      - DRONE_USER_CREATE=username:${ADMIN},admin:true      
      - DRONE_RUNNER_CAPACITY=2      
      - DRONE_GIT_ALWAYS_AUTH=true       
      # Github Config      
      - DRONE_GITHUB_SERVER=https://github.com      
      - DRONE_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}      
      - DRONE_GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}      
      - DRONE_USER_FILTER=${AUTH_USER}  
  drone-agent:    
    image: drone/agent:1    
    restart: always    
    depends_on:      
      - drone-server    
    volumes:      
      - /var/run/docker.sock:/var/run/docker.sock    
    environment:      
      - DRONE_RPC_SERVER=drone-server      
      - DRONE_RUNNER_CAPACITY=4