# Generated by Django 4.1 on 2022-10-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('Site', models.CharField(max_length=20, null=True)),
                ('UserSite', models.CharField(max_length=20, null=True)),
                ('ExportSite', models.CharField(max_length=20, null=True)),
                ('OwnerSite', models.CharField(max_length=20, null=True)),
                ('SEQ', models.IntegerField(blank=True, null=True)),
                ('EQP_ID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('User_EQP_ID', models.CharField(max_length=20, null=True)),
                ('Export_EQP_ID', models.CharField(max_length=20, null=True)),
                ('Owner_EQP_ID', models.CharField(max_length=20, null=True)),
                ('Mobus_Id', models.CharField(max_length=20, null=True)),
                ('ComPort_Id', models.IntegerField(blank=True, null=True)),
                ('DESCRIPTION', models.CharField(max_length=200, null=True)),
                ('EQP_TYPE', models.CharField(max_length=20, null=True)),
                ('EQP_VENDOR', models.CharField(max_length=20, null=True)),
                ('EQP_MODE', models.CharField(max_length=20, null=True)),
                ('EQP_MODEL', models.CharField(max_length=20, null=True)),
                ('EQP_OFFSET', models.IntegerField(blank=True, null=True)),
                ('EQP_WPH', models.FloatField(blank=True, null=True)),
                ('TIMEZONE', models.CharField(max_length=20, null=True)),
                ('TCS_OUTPUT_ACTIVE', models.CharField(max_length=20, null=True)),
                ('TCS_ALARM_ACTIVE', models.CharField(max_length=20, null=True)),
                ('TCS_TOOLHOURLYMOVE_ACTIVE', models.CharField(max_length=20, null=True)),
                ('TCS_LOTHOURLYMOVE_ACTIVE', models.CharField(max_length=20, null=True)),
                ('TCS_DAILYANALYSIS_ACTIVE', models.CharField(max_length=20, null=True)),
                ('TCS_LOTANALYSIS_ACTIVE', models.CharField(max_length=20, null=True)),
                ('LM_TIME', models.DateTimeField(null=True)),
                ('LM_USER', models.CharField(max_length=20, null=True)),
                ('Language', models.CharField(max_length=50, null=True)),
                ('SYS_Status', models.CharField(max_length=20, null=True)),
                ('SYS_DataDeleteDate', models.DateTimeField(null=True)),
                ('SYS_FileImportTime', models.DateTimeField(null=True)),
                ('SYS_WarnKWH', models.IntegerField(null=True)),
                ('SYS_WarnWPH', models.IntegerField(null=True)),
                ('SYS_WarnESH', models.IntegerField(null=True)),
                ('SYS_WarnExpire', models.IntegerField(null=True)),
                ('SYS_WarnCOM', models.IntegerField(null=True)),
                ('SYS_WarnAlarm', models.IntegerField(null=True)),
                ('SYS_WarnTracker', models.IntegerField(null=True)),
                ('SYS_WarnTrackerAlarm', models.IntegerField(null=True)),
                ('SYS_WarnOther', models.IntegerField(null=True)),
                ('MAC', models.CharField(max_length=100, null=True)),
                ('Export_SiteSummary_Date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'equipment',
                'managed': False,
            },
        ),
    ]
